version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: coin
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root     
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password 
    ports:
      - "3306:3306"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
